routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::namespace('FrontEnd')->group(function () {
    // Controllers Within The "App\Http\Controllers\FrontEnd" Namespace
    Route::get('/', 'FrontEndController@index')->name('home');
});

Auth::routes();

Route::middleware('auth')->namespace('Dashboard')->prefix('dashboard')->group(function () {
    // Controllers Within The "App\Http\Controllers\Dashboard" Namespace
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::namespace('Product')->group(function (){
        Route::resource('/product' , 'ProductController');
        Route::post('/buy_product/{product}','ProductController@buy_product')->name('buy_product');
    });
    Route::namespace('User')->group(function (){
        Route::resource('/user' , 'UserController');
    });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'product';
    protected $guarded = [];

    function shoppers()
    {
        return $this->belongsToMany('App\User', 'product_user', 'product_id', 'user_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function products()
    {
        return $this->belongsToMany('App\Product','product_user','user_id','product_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\Support\Renderable;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return Renderable
     */
    public function index()
    {
        return view('Dashboard.index');
    }
}

app/Http/Controllers/Dashboard/Product/ProductController.php
<?php

namespace App\Http\Controllers\Dashboard\Product;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Product;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;

class ProductController extends Controller
{

    public function index()
    {
        $product = Product::all();

        return view('Dashboard.Product.index', compact('product'));
    }

    public function create()
    {
        $product = new Product();
        return view('Dashboard.Product.create', compact('product'));
    }

    public function store()
    {
        $product = new Product();
        $product->name = request('name');
        $product->description = request('description');
        $product->save();
        return redirect('/dashboard/product');
    }

    public function edit(Product $product)
    {
        return view('Dashboard.Product.edit', compact('product'));
    }

    public function update(Product $product)
    {
        $product->name = request('name');
        $product->description = request('description');
        $product->save();
        return redirect('/dashboard/product');
    }

    public function destroy(Product $product)
    {
        $product->delete();
        return redirect('/dashboard/product');
    }

    public function buy_product(Product $product)
    {
        $product->shoppers()->attach(Auth::user()->id);
        return Response::HTTP_OK;
    }
}

app/Http/Controllers/Dashboard/User/UserController.php
<?php

namespace App\Http\Controllers\Dashboard\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
class UserController extends Controller
{
    public function index()
    {
        $user = User::all();
        return view('Dashboard.User.index',compact('user'));
    }
    public function edit(User $user)
    {
        return view('/Dashboard.User.edit',compact('user'));
    }

    public function update(User $user)
    {
        $user->name = request('name');
        $user->email = request('email');
        $user->save();
        return redirect('/dashboard/user');
    }
    public function destroy(User $user)
    {
        $user->delete();
        return redirect('/dashboard/user');
    }
}

app/Http/Controllers/FrontEnd/FrontEndController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Http\Controllers\Controller;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use Illuminate\View\View;
use App\Product;

class FrontEndController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $product = Product::all();
        return view('FrontEnd.index', compact('product'));
    }

}

resources/views/Dashboard/Product/create.blade.php
@extends('layouts.Dashboard.Dashboard')

@section('content')

    <form method="POST" action=" {{ route('product.store') }} ">
        @csrf
        @include('Dashboard.Product.form')
    </form>

@endsection

resources/views/Dashboard/Product/edit.blade.php
@extends('layouts.Dashboard.Dashboard')

@section('content')

    <form method="POST" action=" {{ route('product.update', $product->id) }} ">
        @csrf
        @include('Dashboard.Product.form')
        @method('PATCH')
    </form>

@endsection

resources/views/Dashboard/Product/form.blade.php
<div class="form-group">
    <label for="Product_Name">Product_name</label>
    <input type="text" class="form-control" id="Product_Name" placeholder="name" name="name" value="{{ $product->name }}">
</div>
<div class="form-group">
    <label for="description">description</label>
    <textarea class="form-control" id="description" rows="3" name="description">{{ $product->description }}</textarea>
</div>
<button class="form-control btn btn-primary" type="submit">submit</button>

resources/views/Dashboard/Product/index.blade.php
@extends('layouts.Dashboard.Dashboard')

@section('content')
    <h2>Products List</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Controller</th>
            </tr>
            </thead>
            <tbody>
            @foreach($product as $item)
                <tr>
                    <td>{{ $item->id }}</td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->description }}</td>
                    <td>
                        <div class="row">
                            <div class="col-md-1">
                                <a class="btn btn-primary" href=" {{ route('product.edit',$item->id) }} ">Edit</a>
                            </div>
                            <div class="col-md-2">
                                <a class="btn btn-danger delete-form" role="button" data-id="{{ $item->id }}">Delete</a>
                            </div>
                            <div class="col-md-8">
                                <a class="btn btn-warning" data-toggle="collapse" href="#collapseExample{{$item->id}}"
                                   role="button"
                                   aria-expanded="false" aria-controls="collapseExample">
                                    Shoppers
                                </a>
                                <div class="collapse" id="collapseExample{{$item->id}}">
                                    <div>
                                        @foreach($item->shoppers as $item)
                                            <span class="badge badge-secondary shoppers-badge">{{ $item->name }}</span>
                                        @endforeach
                                    </div>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <a class="btn btn-success" href="{{ route('product.create') }}">Create a new</a>
    </div>
@endsection
@push('scripts')

    <script>
        $('.delete-form').on('click', function () {
            $.ajax({
                type: 'POST',
                url: '/dashboard/product/' + $(this).data('id'),
                data: {_method: 'delete',_token: '{{csrf_token()}}'},
                success: function (data) {
                    alert('Product deleted successfully!');
                    location.reload();
                }
            });
        })
    </script>
@endpush

resources/views/Dashboard/User/edit.blade.php
@extends('layouts.Dashboard.Dashboard')

@section('content')

    <form method="POST" action=" {{ route('user.update',$user->id) }} ">
        @csrf
        @include('Dashboard.User.form')
        @method('PATCH')
    </form>

@endsection

resources/views/Dashboard/User/form.blade.php
<div class="form-group">
    <label for="User_Name">User_name</label>
    <input type="text" class="form-control" id="User_Name" placeholder="name" name="name" value=" {{ $user->name }} ">
</div>
<div class="form-group">
    <label for="email">Email</label>
   <input type="email" class="form-control" id="email" placeholder="Email" name="email" value=" {{ $user->email }} ">
</div>
<button class="form-control btn btn-primary" type="submit">submit</button>

resources/views/Dashboard/User/index.blade.php
@extends('layouts.Dashboard.Dashboard')

@section('content')
    <h2>Customers List</h2>
    <div class="table-responsive">
        <table class="table table-striped table-sm">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Controllers</th>
            </tr>
            </thead>
            <tbody>
            @foreach($user as $item)
                <tr>
                    <td>{{ $item->id }}</td>
                    <td>{{ $item->name }}</td>
                    <td>{{ $item->email }}</td>
                    <td>
                        <a class="btn btn-primary" href="{{ route('user.edit',$item->id) }}">Edit</a>
                        <a class="btn btn-danger delete_user" role="button" data-id="{{ $item->id }}">Delete</a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection
@push('scripts')

    <script>
        $('.delete_user').on('click', function () {
            $.ajax({
                type: 'POST',
                url: '/dashboard/user/' + $(this).data('id'),
                data: {_method: 'delete',_token: '{{csrf_token()}}'},
                success: function (data) {
                    alert('User deleted successfully!');
                    location.reload();
                }
            });
        })
    </script>
@endpush

resources/views/Dashboard/index.blade.php
@extends('layouts.Dashboard.Dashboard')

@section('content')

    <h1 class="">Welcome To Your Dashboard</h1>

@endsection

resources/views/FrontEnd/index.blade.php
@extends('layouts.Frontend.FrontEnd')

@section('content')
    <section class="jumbotron text-center">
        <div class="container">
            <h1>Welcome To My Site</h1>
            <p class="lead text-muted">Overrate to your thoughts, they will be your words, these words will be your
                behavior, overrate to your behavior they will be your personality.</p>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            <div class="row">
                @foreach($product as $item)
                    <div class="col-md-4">
                        <div class="card mb-4 shadow-sm">
                            <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                                 xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice"
                                 focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>
                                    Placeholder</title>
                                <rect width="100%" height="100%" fill="#55595c"/>
                                <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ $item->name }}</text>
                            </svg>
                            <div class="card-body">
                                <p class="card-text">{{ $item->description }}.</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                        <button type="button" class="btn btn-sm btn-outline-secondary buy"
                                                data-id="{{ $item->id }}">Buy
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        $('.buy').on('click', function () {
            $.ajax({
                type: 'POST',
                url: 'dashboard/buy_product/' + $(this).data('id'),
                data:{_token:'{{ csrf_token() }}'},
                success: function (data) {
                    alert('You bought this product successfully!');
                },
                error: function (data) {
                    if(data.status == 401){
                        alert('Please login first');
                    }
                }
            });
        })
    </script>
@endpush

resources/views/layouts/Dashboard/Dashboard.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Dashboard Template · Bootstrap</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/Dashboard/css/main.css') }}" rel="stylesheet">
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <!-- Custom styles for this template -->
    <link href="{{ asset('assets/Dashboard/css/dashboard.css') }}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('dashboard') }}">
                                Dashboard
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#" role="button"
                               onclick="document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="{{ route('dashboard') }}">
                                <span data-feather="home"></span>
                                Dashboard <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('product.index') }}">
                                <span data-feather="shopping-cart"></span>
                                Products
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('user.index') }}">
                                <span data-feather="users"></span>
                                Customers
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">

                @yield('content')

            </main>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
    <script src="{{ asset('/assets/Dashboard/js/bootstrap.bundle.min.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="{{asset('/assets/Dashboard/js/dashboard.js')}}"></script>
@stack('scripts')
</body>
</html>

resources/views/layouts/Frontend/FrontEnd.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('dashboard') }}">
                                    Dashboard
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#" role="button" onclick="document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main>
            @yield('content')
        </main>
    </div>

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>

    @stack('script')
</body>
</html>